name: E2E tests

on:

  push:
  pull_request:

env:
  OC_SERVER_URL: https://188.245.37.132:9200

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: checkout
        uses: actions/checkout@v4
      #- name: Install and Run Appium Server
      #  run: |
      #    brew install ios-deploy
      #    brew install carthage
      #    chmod +x ./runAppium.sh # install and run appium server in the background
      #    ./runAppium.sh
      - name: Run simulator
        uses: futureware-tech/simulator-action@v4
        with:
          os: 'iOS'
          model: 'iPhone 15'
          os_version: '17.2'
          wait_for_boot: 'true'
          udid: '295CA147-D5E2-46D6-B6DD-E2D4397CC460'
          shutdown_after_job: 'true'
      - name: Check if device is booted
        run: |
          xcrun simctl list | grep -i booted          
      #- name: Clone WebDriverAgent
      #  run: |
      #    git clone https://github.com/appium/WebDriverAgent.git
      #    cd WebDriverAgent && git submodule update --init --recursive
      #    pwd
      #- name: Verify WebDriverAgent
      #  run: |
      #    ls -l $(npm root -g)/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
      #- name: Install WebDriverAgent
      #  run: |
      #    cd WebDriverAgent 
      #    xcodebuild -project WebDriverAgent.xcodeproj \
      #    -scheme WebDriverAgentRunner \
      #    -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
      #    build-for-testing
      #- name: Start WebDriverAgent
      #  run: |
      #    cd WebDriverAgent 
      #    xcodebuild -project WebDriverAgent.xcodeproj \
      #    -scheme WebDriverAgentRunner \
      #    -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
      #    test-without-building
      #- name: Grant permissions to WebDriverAgent
      #  run: |
      #    cd WebDriverAgent 
      #    tccutil reset All com.apple.WebDriverAgentRunner
      - name: Run Tests
        run: |
          brew install ios-deploy
          brew install carthage
          chmod +x ./runAppium.sh # install and run appium server in the background
          ./runAppium.sh
          sleep 10
          ./executeTests -t @createfolder
